version: "3.8"

services:
  api:
    container_name: api
    image: api:1.0.0
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./api:/usr/src/app
    env_file:
      - .env
    networks:
      - podgrasp-network
  client:
    container_name: client
    image: client:1.0.0
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - podgrasp-network
networks:
  podgrasp-network:
